services:
  segmentdrop:
    image: chenvd/segmentdrop:latest
    container_name: segmentdrop
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    mem_limit: 256m
